config/routes.rb
PluploadExample::Application.routes.draw do
  root :to => 'photos#index'
  
  resources :photos, :only => [:index, :create]
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :file
  
  has_attached_file :file, :styles => { 
                              :thumb => "100x100#",
                              :normal => "600x600>", 
                              },
                            :url => "/system/photos/:id/:style.:extension",
                            :path => ":rails_root/public/system/photos/:id/:style.:extension"
                            
  validates_attachment_presence :file
  validates_attachment_content_type :file, :content_type => [/image\/jpg/, /image\/jpeg/, /image\/pjpeg/, /image\/gif/, /image\/png/, /image\/x-png/]
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  def index
    @photos = Photo.all
  end
  
  def create
    @photo = Photo.new
    @photo.file = params[:file] if params.has_key?(:file)
    # detect Mime-Type (mime-type detection doesn't work in flash)
    @photo.file_content_type = MIME::Types.type_for(params[:name]).to_s if params.has_key?(:name)
    @photo.save!
    
    respond_to :js
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  def flash_notice
    html = ''
    flash.each do |name, msg|
      html += content_tag :div, msg, :class => name
    end
    html.html_safe
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Plupload example - Rails 3
    %meta{'http-equiv' => 'Content-Type', :content => 'text/html;charset=utf-8'}
    = stylesheet_link_tag 'application'
    = javascript_include_tag "jquery.min", "rails", "application", :cache => "application_all"
    = csrf_meta_tag
    = yield :head
  %body
    #content
      #flash= flash_notice if flash.present?
      = yield

app/views/photos/_photo.html.haml
.photo= image_tag(photo.file.url(:thumb))

app/views/photos/_plupload.js.erb
<% session_key_name = Rails.application.config.session_options[:key] %>
jQuery(document).ready(function() {
  $("#uploader").pluploadQueue({
    runtimes: 'html5,flash,silverlight',
    url: '<%= photos_path %>',
    max_file_size: '10mb',
    multiple_queues: true,
    flash_swf_url: "/javascripts/plupload/plupload.flash.swf",  
    silverlight_xap_url: "/javascripts/plupload/plupload.silverlight.xap",
    multipart: true,
    multipart_params: {
      '_http_accept': 'application/javascript',
      'authenticity_token' : '<%= form_authenticity_token %>',
      '<%= session_key_name %>' : encodeURIComponent('<%= u cookies[session_key_name] %>')
    },
    filters: [
      {title: "Images", extensions: "jpg,jpeg,png"}
    ],
    init: {
      FileUploaded: function(up, file, info) {
        eval(info["response"]);
      }
    }
  });
});

app/views/photos/create.js.erb
$('#photos_container').append('<%= escape_javascript render("photo", :photo => @photo) %>');

app/views/photos/index.html.haml
- content_for :head do
  = stylesheet_link_tag "plupload.queue"
  = javascript_include_tag "plupload/plupload.full.min", "plupload/jquery.plupload.queue.min"
  = javascript_tag do
    = render "plupload.js"
    

#photos_container
  = render :partial => "photo", :collection => @photos
    
#uploader
  %p You browser doesn't have HTML5, Flash or Silverlight support.